#!/bin/sh

mkdir -p /var/log/cb/integrations/infoblox/
touch /var/log/cb/integrations/infoblox/infoblox.log
mkdir -p /usr/share/cb/integrations/infoblox/feeds/

chown -R cb:cb /var/log/cb/integrations/infoblox
chown -R cb:cb /usr/share/cb/integrations/infoblox/feeds/
chmod +x /usr/share/cb/integrations/infoblox/cbinfoblox