#!/usr/bin/env python


import sys
import cbinfoblox.version
import cbinfoblox.bridge

sys.path.insert(0, "src/")

if __name__ == "__main__":
    name = "cb-infoblox-bridge"
    daemon = cbinfoblox.bridge.InfobloxBridge(name, "root/etc/cb/integrations/infoblox/infoblox.conf")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, cbinfoblox.version.__version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

    sys.exit(0)